name: E2E
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Appium_Android:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    env:
      ANDROID_DEVICE_NAME: TestEmulatorApp
      ANDROID_PLATFORM_VERSION: 11.0
      ANDROID_APP_PATH: src/test/java/resources/Android.SauceLabs.Mobile.Sample.app.2.7.1.apk
      ANDROID_APP_PACKAGE: com.swaglabsmobileapp
      ANDROID_APP_ACTIVITY: com.swaglabsmobileapp.MainActivity
      ANDROID_AUTOMATION_NAME: UiAutomator2

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Setup Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Appium
        uses: FinbertMDS/setup-appium@latest

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 30

      - name: Setup Android PATH
        run: |
          echo "ANDROID_SDK_ROOT=$ANDROID_HOME" >> $GITHUB_ENV
          echo "ANDROID_AVD_HOME=$HOME/.android/avd" >> $GITHUB_ENV
          echo "$ANDROID_HOME/emulator:$ANDROID_HOME/platform-tools:$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH

      - name: Create Android Emulator
        run: |
          yes | sdkmanager --licenses || true
          sdkmanager "system-images;android-30;google_apis;x86_64"
          mkdir -p $HOME/.android/avd
          printf "no\n" | avdmanager create avd -n $ANDROID_DEVICE_NAME -k "system-images;android-30;google_apis;x86_64" --device "pixel"
          echo "Available AVDs:"
          emulator -list-avds

      - name: Start Emulator
        run: |
          echo "Listing available AVDs before start:"
          emulator -list-avds
          echo "Starting emulator: $ANDROID_DEVICE_NAME"
          emulator -avd $ANDROID_DEVICE_NAME -no-window -no-audio -no-accel -no-metrics &
          adb wait-for-device
          timeout 300 bash -c 'until adb shell getprop sys.boot_completed | grep -q 1; do sleep 2; done'

      - name: Run Appium E2E Tests
        run: |
          npx appium &
          sleep 15
          mvn -Dtest="E2E" clean test
        continue-on-error: true

      - name: Stop Emulator
        if: always()
        run: |
          adb emu kill || true
          pkill -f emulator || true

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Appium_AndroidReport
          path: "Test-out/allure-results"